default_platform(:ios)

platform :ios do
  desc "Build iOS app"
  lane :build do
    build_app(
      scheme: "Runner",
      export_method: "app-store"
    )
  end

  desc "Upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_KEY_BASE64'],
      is_key_content_base64: true
    )

    build_app(
      scheme: "Runner",
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: api_key,
      distribute_external: true,
      skip_waiting_for_build_processing: true
    )
  end
end
