name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: runnerprime-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

  distribute:
    if: ${{ github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder for Firebase App Distribution
        run: |
          echo "Add Firebase App Distribution step here using secrets: FIREBASE_TOKEN, APP_ID"

