name: iOS TestFlight

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
      - name: Install Ruby and Fastlane
        run: |
          sudo gem install fastlane --no-document
      - name: Flutter pub get
        run: flutter pub get
      - name: Build and upload to TestFlight
        working-directory: ios
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_BASE64: ${{ secrets.ASC_KEY_BASE64 }}
        run: |
          fastlane beta

